### ISSUE TITLE
Bugs when running the trainning dataset

### ISSUE THREAD

**Issue by wangmiaowei** [Sangluisme/Implicit-surf-Deformation#1]
Great job thanks for your opensourcing of this project. As titled, I encountered a bug in the trainning dataset, I am not familiar with this archicture, could you give some hints? 

python train.py --conf ./conf/faust.conf --savedir ./exp --expname faust_r --subindex 4 --reset

![Image](https://github.com/user-attachments/assets/b37748ab-ad77-444d-8489-87b30b334460)

**Comment by Sangluisme** [comment]
ah, I think it is due to cuda being out of memory. In faust.conf, we set T=30 for the best rendering quality and we run it in a slurm system. If you run it on your computer, please reduce T=5 or T=10.

**Comment by WeiZhang511** [comment]
i think it's probably due to a mismatch between the JAX and CUDA versions(and cudnn), after i created correct env, it worked smoothly

**Comment by wangmiaowei** [comment]
Thanks for your reply, I will spend time doing that. I am not familiar with JAX. My machine is 4090. Btw, will u release the pretrained model for the further research?

**Comment by jpsml** [comment]
> i think it's probably due to a mismatch between the JAX and CUDA versions(and cudnn), after i created correct env, it worked smoothly

@WeiZhang511 , would you please provide the versions of the libraries that you are using in your env (e.g. jax, cuda, cudnn, python, etc.)? I am also having the same segmentation fault issue in my environment.

**Comment by WeiZhang511** [comment]
> > i think it's probably due to a mismatch between the JAX and CUDA versions(and cudnn), after i created correct env, it worked smoothly
> 
> [@WeiZhang511](https://github.com/WeiZhang511) , would you please provide the versions of the libraries that you are using in your env (e.g. jax, cuda, cudnn, python, etc.)? I am also having the same segmentation fault issue in my environment.

Jaxlib >> > Version: 0.4.25+cuda12.cudnn89
Jax >>> Version: 0.4.25
Python 3.10.15
cuda/12.3.1
cudnn/v8.9.6.50
In my case, since I’m using SLURM from the chair’s cluster, I need to run commands like module load cuda/12.3.1 cudnn/v8.9.6.50 before executing the code. Otherwise, the code will default to running on the CPU, which is significantly slower. Hope this is helpful for you!

**Comment by jpsml** [comment]
Thank you. Even following your env config, I was not able to run using GPU. And even when running on CPU, it is not working, it gives the message below after 4k epochs:

laplacian: 0.0002488717727828771	
loss: 0.01350618526339531	
match: 4.264375093043782e-05	
 33%|█████████████████████████████████████████████████████▉                                                                                                            | 4000/12001 [15:36<30:06,  4.43it/s]
could not append a binary post-op

**Comment by WeiZhang511** [comment]
Yes, you're right, this issue happens when you run it on CPU, running on GPU would not cause such a problem. How did you install your Jax? Have you tried "pip install --upgrade "jax[cuda12_pip]==0.4.25" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"? You can also refer to: https://github.com/jax-ml/jax/issues/18027

**Comment by jpsml** [comment]
Followed your instructions, now I am getting the following error:

```
2025-06-03 15:57:53.906653: I external/xla/xla/stream_executor/cuda/cuda_dnn.cc:517] Loaded cuDNN version 8907
[cuda(id=0)]
WARNING:absl:Configured `CheckpointManager` using deprecated legacy API. Please follow the instructions at https://orbax.readthedocs.io/en/latest/api_refactor.html to migrate by May 1st, 2024.
 train for 0 -----> 4...............
WARNING:absl:SaveArgs.aggregate is deprecated, please use custom TypeHandler (https://orbax.readthedocs.io/en/latest/custom_handlers.html#typehandler) or contact Orbax team to migrate before May 1st, 2024.
  0%|                                                                                                                                                                             | 0/12001 [00:00<?, ?it/s]2025-06-03 15:57:58.656256: F external/xla/xla/service/gpu/triton_autotuner.cc:624] Non-OK-status: has_executable.status() status: INTERNAL: ptxas exited with non-zero error code 139, output: : If the error message indicates that a file could not be written, please verify that sufficient filesystem space is provided.Failure occured when compiling fusion triton_gemm_dot.258 with config '{block_m:128,block_n:16,block_k:128,split_k:1,num_stages:4,num_warps:4,num_ctas:1}'
Fused HLO computation:
%triton_gemm_dot.258_computation (parameter_0.7: f32[2000,256], parameter_1.7: f32[256], parameter_2.6: f32[256,3]) -> f32[2000,3] {
  %parameter_0.7 = f32[2000,256]{1,0} parameter(0)
  %parameter_1.7 = f32[256]{0} parameter(1)
  %broadcast.370 = f32[2000,256]{1,0} broadcast(f32[256]{0} %parameter_1.7), dimensions={1}, metadata={op_name="jit(train_step_frozen_sdf)/jit(main)/jvp(MLP)/dense_7/add" source_file="/home/joaopaulolima/Implicit-surf-Deformation/models/modules.py" source_line=115}
  %add.408 = f32[2000,256]{1,0} add(f32[2000,256]{1,0} %parameter_0.7, f32[2000,256]{1,0} %broadcast.370), metadata={op_name="jit(train_step_frozen_sdf)/jit(main)/jvp(MLP)/dense_7/add" source_file="/home/joaopaulolima/Implicit-surf-Deformation/models/modules.py" source_line=115}
  %constant.190 = f32[] constant(0)
  %broadcast.371 = f32[2000,256]{1,0} broadcast(f32[] %constant.190), dimensions={}, metadata={op_name="jit(train_step_frozen_sdf)/jit(main)/jvp(MLP)/jit(relu)/max" source_file="/home/joaopaulolima/Implicit-surf-Deformation/models/modules.py" source_line=116}
  %maximum.168 = f32[2000,256]{1,0} maximum(f32[2000,256]{1,0} %add.408, f32[2000,256]{1,0} %broadcast.371), metadata={op_name="jit(train_step_frozen_sdf)/jit(main)/jvp(MLP)/jit(relu)/max" source_file="/home/joaopaulolima/Implicit-surf-Deformation/models/modules.py" source_line=116}
  %parameter_2.6 = f32[256,3]{1,0} parameter(2)
  ROOT %dot.97 = f32[2000,3]{1,0} dot(f32[2000,256]{1,0} %maximum.168, f32[256,3]{1,0} %parameter_2.6), lhs_contracting_dims={1}, rhs_contracting_dims={0}, metadata={op_name="jit(train_step_frozen_sdf)/jit(main)/jvp(MLP)/dense_9/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/joaopaulolima/Implicit-surf-Deformation/models/modules.py" source_line=121}
}
```

My env is as follows:

```
# pip list | grep jax
jax                      0.4.25
jaxlib                   0.4.25+cuda12.cudnn89
# pip list |grep nvidia
nvidia-cublas-cu12       12.3.4.1
nvidia-cuda-cupti-cu12   12.3.101
nvidia-cuda-nvcc-cu12    12.3.107
nvidia-cuda-nvrtc-cu12   12.3.107
nvidia-cuda-runtime-cu12 12.3.101
nvidia-cudnn-cu12        8.9.7.29
nvidia-cufft-cu12        11.0.12.1
nvidia-curand-cu12       10.3.4.107
nvidia-cusolver-cu12     11.5.4.101
nvidia-cusparse-cu12     12.2.0.103
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.3.101
```

**Comment by jpsml** [comment]
@WeiZhang511 , would you please send the output of the commands `pip list | grep jax` and `pip list |grep nvidia` in your env?

**Comment by WeiZhang511** [comment]
Sure, 
```bash
pip list | grep jax
jax                      0.4.25
jaxlib                   0.4.25+cuda12.cudnn89

pip list | grep nvidia
nvidia-cublas-cu12       12.6.4.1
nvidia-cuda-cupti-cu12   12.6.80
nvidia-cuda-nvcc-cu12    12.6.85
nvidia-cuda-runtime-cu12 12.6.77
nvidia-cudnn-cu12        9.6.0.74
nvidia-cufft-cu12        11.3.0.4
nvidia-cusolver-cu12     11.7.1.2
nvidia-cusparse-cu12     12.5.4.2
nvidia-nccl-cu12         2.23.4
nvidia-nvjitlink-cu12    12.6.85
```

**Comment by Sangluisme** [comment]
> Thank you. Even following your env config, I was not able to run using GPU. And even when running on CPU, it is not working, it gives the message below after 4k epochs:
> 
> laplacian: 0.0002488717727828771 loss: 0.01350618526339531 match: 4.264375093043782e-05 33%|█████████████████████████████████████████████████████▉ | 4000/12001 [15:36<30:06, 4.43it/s] could not append a binary pos

I haven't tried CPU version. Let me try once. 
Plus, 

> Followed your instructions, now I am getting the following error:
> 
> ```
> 2025-06-03 15:57:53.906653: I external/xla/xla/stream_executor/cuda/cuda_dnn.cc:517] Loaded cuDNN version 8907
> [cuda(id=0)]
> WARNING:absl:Configured `CheckpointManager` using deprecated legacy API. Please follow the instructions at https://orbax.readthedocs.io/en/latest/api_refactor.html to migrate by May 1st, 2024.
>  train for 0 -----> 4...............
> WARNING:absl:SaveArgs.aggregate is deprecated, please use custom TypeHandler (https://orbax.readthedocs.io/en/latest/custom_handlers.html#typehandler) or contact Orbax team to migrate before May 1st, 2024.
>   0%|                                                                                                                                                                             | 0/12001 [00:00<?, ?it/s]2025-06-03 15:57:58.656256: F external/xla/xla/service/gpu/triton_autotuner.cc:624] Non-OK-status: has_executable.status() status: INTERNAL: ptxas exited with non-zero error code 139, output: : If the error message indicates that a file could not be written, please verify that sufficient filesystem space is provided.Failure occured when compiling fusion triton_gemm_dot.258 with config '{block_m:128,block_n:16,block_k:128,split_k:1,num_stages:4,num_warps:4,num_ctas:1}'
> Fused HLO computation:
> %triton_gemm_dot.258_computation (parameter_0.7: f32[2000,256], parameter_1.7: f32[256], parameter_2.6: f32[256,3]) -> f32[2000,3] {
>   %parameter_0.7 = f32[2000,256]{1,0} parameter(0)
>   %parameter_1.7 = f32[256]{0} parameter(1)
>   %broadcast.370 = f32[2000,256]{1,0} broadcast(f32[256]{0} %parameter_1.7), dimensions={1}, metadata={op_name="jit(train_step_frozen_sdf)/jit(main)/jvp(MLP)/dense_7/add" source_file="/home/joaopaulolima/Implicit-surf-Deformation/models/modules.py" source_line=115}
>   %add.408 = f32[2000,256]{1,0} add(f32[2000,256]{1,0} %parameter_0.7, f32[2000,256]{1,0} %broadcast.370), metadata={op_name="jit(train_step_frozen_sdf)/jit(main)/jvp(MLP)/dense_7/add" source_file="/home/joaopaulolima/Implicit-surf-Deformation/models/modules.py" source_line=115}
>   %constant.190 = f32[] constant(0)
>   %broadcast.371 = f32[2000,256]{1,0} broadcast(f32[] %constant.190), dimensions={}, metadata={op_name="jit(train_step_frozen_sdf)/jit(main)/jvp(MLP)/jit(relu)/max" source_file="/home/joaopaulolima/Implicit-surf-Deformation/models/modules.py" source_line=116}
>   %maximum.168 = f32[2000,256]{1,0} maximum(f32[2000,256]{1,0} %add.408, f32[2000,256]{1,0} %broadcast.371), metadata={op_name="jit(train_step_frozen_sdf)/jit(main)/jvp(MLP)/jit(relu)/max" source_file="/home/joaopaulolima/Implicit-surf-Deformation/models/modules.py" source_line=116}
>   %parameter_2.6 = f32[256,3]{1,0} parameter(2)
>   ROOT %dot.97 = f32[2000,3]{1,0} dot(f32[2000,256]{1,0} %maximum.168, f32[256,3]{1,0} %parameter_2.6), lhs_contracting_dims={1}, rhs_contracting_dims={0}, metadata={op_name="jit(train_step_frozen_sdf)/jit(main)/jvp(MLP)/dense_9/dot_general[dimension_numbers=(((1,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/joaopaulolima/Implicit-surf-Deformation/models/modules.py" source_line=121}
> }
> ```
> 
> My env is as follows:
> 
> ```
> # pip list | grep jax
> jax                      0.4.25
> jaxlib                   0.4.25+cuda12.cudnn89
> # pip list |grep nvidia
> nvidia-cublas-cu12       12.3.4.1
> nvidia-cuda-cupti-cu12   12.3.101
> nvidia-cuda-nvcc-cu12    12.3.107
> nvidia-cuda-nvrtc-cu12   12.3.107
> nvidia-cuda-runtime-cu12 12.3.101
> nvidia-cudnn-cu12        8.9.7.29
> nvidia-cufft-cu12        11.0.12.1
> nvidia-curand-cu12       10.3.4.107
> nvidia-cusolver-cu12     11.5.4.101
> nvidia-cusparse-cu12     12.2.0.103
> nvidia-nccl-cu12         2.19.3
> nvidia-nvjitlink-cu12    12.3.101
> ```

can you try to add this on train.py file:

os.environ["XLA_FLAGS"] = "--xla_gpu_enable_triton_gemm=false"

**Comment by jpsml** [comment]
Thank you very much, this fixed my issue:
os.environ["XLA_FLAGS"] = "--xla_gpu_enable_triton_gemm=false"

Is this the expected result for the faust_r experiment described in the readme?
![Image](https://github.com/user-attachments/assets/240ad3d3-c823-4cbd-8484-37238eb63839)

**Comment by Sangluisme** [comment]
> Thank you very much, this fixed my issue: os.environ["XLA_FLAGS"] = "--xla_gpu_enable_triton_gemm=false"
> 
> Is this the expected result for the faust_r experiment described in the readme? ![Image](https://github.com/user-attachments/assets/240ad3d3-c823-4cbd-8484-37238eb63839) [ ![Image](https://github.com/user-attachments/assets/240ad3d3-c823-4cbd-8484-37238eb63839) ](https://private-user-images.githubusercontent.com/13179144/451397263-240ad3d3-c823-4cbd-8484-37238eb63839.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDkwNzE3NDUsIm5iZiI6MTc0OTA3MTQ0NSwicGF0aCI6Ii8xMzE3OTE0NC80NTEzOTcyNjMtMjQwYWQzZDMtYzgyMy00Y2JkLTg0ODQtMzcyMzhlYjYzODM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjA0VDIxMTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZTQ4MzAwMzkyZWM3MGUzMWM5ZGNiYTRhNzhjODVjNzhlNGQ3MWQzM2Y2OGYwN2E3MmE2OWRjMDVmZmMyMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.twKxtUfomVh5OyAj9shtEMSCaApPyyjERRSkd3I3TS0) [ ](https://private-user-images.githubusercontent.com/13179144/451397263-240ad3d3-c823-4cbd-8484-37238eb63839.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDkwNzE3NDUsIm5iZiI6MTc0OTA3MTQ0NSwicGF0aCI6Ii8xMzE3OTE0NC80NTEzOTcyNjMtMjQwYWQzZDMtYzgyMy00Y2JkLTg0ODQtMzcyMzhlYjYzODM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjA0VDIxMTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZTQ4MzAwMzkyZWM3MGUzMWM5ZGNiYTRhNzhjODVjNzhlNGQ3MWQzM2Y2OGYwN2E3MmE2OWRjMDVmZmMyMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.twKxtUfomVh5OyAj9shtEMSCaApPyyjERRSkd3I3TS0)

Yes, pretty much it. Still small artifacts around fingers, which can probably be improved by 
1. Fine-tuning weights for each loss term
2. Add more fine-tuning steps during training.

But as the deformation is already physically plausible, so I would saw it is the expected result.
